global:
  scrape_interval: 15s 

scrape_configs:
  - job_name: 'Building Store Prometheus'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['slim-blythe-williamalxndr-aab64bd4.koyeb.app']
        labels:
          application: 'My Spring Boot Application'
